print(root.data)
    # preorder(root)
    # print()
    # inorder(root)
    # print()
    # postorder(root)
    # print()
    # levelorder(root)
    # print()
    # print(countNodes(root))
    # print(sumOfNodes(root))
    # print(height(root))